const fs = require('fs');
const path = require('path');

const syllabusData = JSON.parse(fs.readFileSync('./src/data/syllabus_data.json', 'utf8'));
const syllabusMap = new Map();
syllabusData.forEach((c) => {
  syllabusMap.set(c['科目名'], c);
  const norm = c['科目名'].replace(/\s+/g, '').replace(/（/g, '(').replace(/）/g, ')');
  syllabusMap.set(norm, c);
});

function getCleanSubjectName(rawName) {
  const trimmed = rawName.trim();
  if (syllabusMap.has(trimmed)) return trimmed;
  const match = trimmed.match(/基礎科目（[^：:]+[：:](.+)）/);
  if (match && syllabusMap.has(match[1])) return match[1];
  return trimmed;
}

function buildEntry(rawName, year, quarterStr, notes) {
  const cleanName = getCleanSubjectName(rawName);
  const course = syllabusMap.get(cleanName);
  const credits = course ? course['単位数'] : 2;
  const category = course ? course['科目区分'] || course['科目分類'] || '展開科目' : '導入科目';
  const domain = course ? course['学問分野名'] || '情報' : '導入';
  return {
    subjectRaw: cleanName,
    subjectName: cleanName,
    year,
    quarterStr,
    credits,
    category,
    domain,
    notes: notes || '',
  };
}

const metadataMap = {
  'データサイエンス・AI': {
    id: 'ds-ai',
    tagline: 'データ分析・機械学習・ディープラーニングを修得する先端ITコース',
    iconName: 'Brain',
    gradient: 'linear-gradient(135deg, #06b6d4 0%, #2563eb 100%)',
  },
  'Web・アプリ開発プログラミング': {
    id: 'web-app',
    tagline: 'フロントエンド・バックエンド・セキュリティまで網羅する実践型エンジニアコース',
    iconName: 'Code',
    gradient: 'linear-gradient(135deg, #10b981 0%, #0d9488 100%)',
  },
  'デジタルコンテンツ・デザイン表現': {
    id: 'digital-content',
    tagline: '画像・3D・アニメ・WEBコミックの表現技法とクリエイティブを学ぶコース',
    iconName: 'Palette',
    gradient: 'linear-gradient(135deg, #d946ef 0%, #ec4899 100%)',
  },
  'ビジネス・マーケティング・イノベーション': {
    id: 'business-marketing',
    tagline: '経済学・マーケティング・スタートアップ経営を統合したイノベーターコース',
    iconName: 'TrendingUp',
    gradient: 'linear-gradient(135deg, #f59e0b 0%, #ea580c 100%)',
  },
  '人文・社会・現代教養': {
    id: 'humanities-social',
    tagline: '哲学・社会学・人類学を通じ、複雑な現代社会を俯瞰する教養コース',
    iconName: 'BookOpen',
    gradient: 'linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)',
  },
  '現代数理科学・理論探究': {
    id: 'math-science',
    tagline: '線形代数・解析学・抽象代数・記号論理の数理的思考を深化させるコース',
    iconName: 'Binary',
    gradient: 'linear-gradient(135deg, #6366f1 0%, #1d4ed8 100%)',
  },
  '地域創生・アグリ＆スマートローカル': {
    id: 'regional-creation',
    tagline: 'アグリテック・地域イノベーション・ローカル活性化を目指す地域創生コース',
    iconName: 'Leaf',
    gradient: 'linear-gradient(135deg, #22c55e 0%, #047857 100%)',
  },
  '情報セキュリティ・サイバー社会安全保障': {
    id: 'info-security',
    tagline: 'ネットワーク・Linux・Webセキュリティと安全保障を修得するセキュリティコース',
    iconName: 'ShieldCheck',
    gradient: 'linear-gradient(135deg, #ef4444 0%, #be123c 100%)',
  },
  'コンテンツ・プロデュース＆知財メディアビジネス': {
    id: 'content-produce',
    tagline: 'マンガ・アニメ・ネット文化の企画立案・プロデュース・知財流通を学ぶコース',
    iconName: 'Film',
    gradient: 'linear-gradient(135deg, #a855f7 0%, #db2777 100%)',
  },
  '認知科学・ヒューマンインターフェース': {
    id: 'cognitive-science',
    tagline: '認知神経科学・心理学・AIと人間中心設計（UI/UX）を結ぶ学術コース',
    iconName: 'Cpu',
    gradient: 'linear-gradient(135deg, #0284c7 0%, #4338ca 100%)',
  },
  'ソーシャルデザイン・未来社会構想': {
    id: 'social-design',
    tagline: 'SF思考・未来社会デザイン・現代社会理論で理想の社会を設計するコース',
    iconName: 'Compass',
    gradient: 'linear-gradient(135deg, #14b8a6 0%, #0369a1 100%)',
  },
};

const rawModelsData = {
  'データサイエンス・AI': [
    buildEntry('アカデミックリテラシー', 1, '1Q', '必修'),
    buildEntry('ITリテラシー', 1, '1Q', '必修'),
    buildEntry('人文社会入門', 1, '1Q', '導入要件'),
    buildEntry('人工知能活用実践', 1, '1-2Q', '導入要件(多言語前提)'),
    buildEntry('経済入門', 1, '2Q', '導入要件'),
    buildEntry('基礎科目（情報：データサイエンス概論）', 1, '2Q', '基礎科目要件'),
    buildEntry('デジタルツールの使い方', 1, '2Q', '必修'),
    buildEntry('多言語ITコミュニケーション', 1, '3Q', '必修(ツール修得後)'),
    buildEntry('基礎科目（数理：数学の方法）', 1, '2Q', '数理基礎'),
    buildEntry('基礎科目（文化・思想：心理学）', 1, '2Q', '基礎科目要件'),
    buildEntry('基礎科目（経済：企業経営）', 1, '4Q', '基礎科目要件'),
    buildEntry('現代社会と数学', 1, '1Q', '【置換】導入選択(社会と数学)'),
    buildEntry('線形代数1', 1, '3Q', '基盤数理'),
    buildEntry('基礎科目（数理：初等代数概論）', 1, '3Q', '基礎科目要件'),
    buildEntry('基礎科目（社会・NW：社会学Ⅰ）', 1, '3Q', '基礎科目要件'),
    buildEntry('マンガ産業史', 1, '3Q', 'デジタル産業指定要件'),
    buildEntry('基礎科目（数理：数学史）', 1, '3Q', '基礎科目要件'),
    buildEntry('Pythonプログラミング', 1, '4Q', 'プログラミング基礎'),
    buildEntry('解析学1', 1, '4Q', '基盤数理'),
    buildEntry('統計学入門', 2, '1Q', '【追加】データ分析前提(DS概論・解析1修得後)'),
    buildEntry('機械学習概論', 2, '1Q', 'AI専門'),
    buildEntry('線形代数2', 2, '1Q', '基盤数理'),
    buildEntry('コンピューターサイエンス概論', 2, '1Q', 'CS基礎'),
    buildEntry('ビッグデータ分析概論', 2, '1Q', 'データ分析専門'),
    buildEntry('解析学2', 2, '2Q', '基盤数理'),
    buildEntry('ミクロ経済学', 2, '2Q', '世界理解'),
    buildEntry('意思決定の能力開発', 2, '2Q', '世界理解'),
    buildEntry('計算機実験で学ぶ確率とモンテカルロ法', 2, '3Q', '情報演習'),
    buildEntry('機械翻訳実践（情報）', 2, '1-2Q', '多言語要件'),
    buildEntry('Inter-universal Teichmüller Theory 2（宇宙際タイヒミューラー理論 2）', 2, '1-2Q', '先端数理(IUT1修得後)'),
    buildEntry('ディープラーニング1', 2, '3Q', 'AI専門'),
    buildEntry('科学哲学', 2, '3Q', '世界理解'),
    buildEntry('データベース運用実践', 2, '4Q', 'DB専門'),
    buildEntry('AIアルゴリズム実践', 2, '3-4Q', '考究科目'),
    buildEntry('マーケティング × データサイエンス', 2, '3-4Q', '考究科目(統計学前提達成)'),
    buildEntry('数理科学発展演習Ⅰ', 2, '3-4Q', '考究科目(基礎数理完結後)'),
    buildEntry('Inter-universal Teichmüller Theory 3（宇宙際タイヒミューラー理論 3）', 2, '3-4Q', '先端数理(IUT1,2修得後)'),
    buildEntry('機械翻訳実践（自然科学）', 2, '3-4Q', '多言語要件'),
    buildEntry('プロジェクト実践', 4, '1-4Q', '卒業プロジェクト(1~4Q通年・4単位)'),
  ],

  'Web・アプリ開発プログラミング': [
    buildEntry('アカデミックリテラシー', 1, '1Q', '必修'),
    buildEntry('ITリテラシー', 1, '1Q', '必修'),
    buildEntry('Webアプリケーション開発1', 1, '1Q', 'Web開発基礎'),
    buildEntry('人文社会入門', 1, '1Q', '導入要件'),
    buildEntry('人工知能活用実践', 1, '1-2Q', '導入要件(多言語前提)'),
    buildEntry('経済入門', 1, '2Q', '導入要件'),
    buildEntry('デジタルツールの使い方', 1, '2Q', '必修'),
    buildEntry('多言語ITコミュニケーション', 1, '3Q', '必修(ツール修得後)'),
    buildEntry('基礎科目（数理：数学の方法）', 1, '2Q', '基礎科目要件'),
    buildEntry('Webアプリケーション開発2', 1, '2Q', '【追加】フロントエンド実践'),
    buildEntry('現代社会と数学', 1, '1Q', '【置換】導入選択(社会と数学)'),
    buildEntry('基礎科目（情報：情報セキュリティ概論）', 1, '3Q', '基礎科目要件'),
    buildEntry('基礎科目（数理：初等代数概論）', 1, '3Q', '暗号数理の準備'),
    buildEntry('基礎科目（数理：数学史）', 1, '3Q', '基礎科目要件'),
    buildEntry('基礎科目（社会・NW：社会学Ⅰ）', 1, '3Q', '基礎科目要件'),
    buildEntry('IT産業史', 1, '3Q', 'デジタル産業指定要件'),
    buildEntry('基礎科目（数理：数学史）', 1, '3Q', '基礎科目要件'),
    buildEntry('Webアプリケーション開発3', 1, '3Q', '【追加】バックエンド・API開発'),
    buildEntry('基礎科目（数理：数学史）', 1, '3Q', '基礎科目要件'),
    buildEntry('Pythonプログラミング', 1, '4Q', '展開科目'),
    buildEntry('基礎科目（文化・思想：哲学概論）', 1, '4Q', '基礎科目要件'),
    buildEntry('基礎科目（文化・思想：心理学）', 1, '4Q', '基礎科目要件'),
    buildEntry('基礎科目（経済：企業経営）', 1, '4Q', '基礎科目要件'),
    buildEntry('基礎科目（経済：企業経営）', 1, '4Q', '基礎科目要件'),
    buildEntry('二次創作の歴史から見るネット文化', 1, '3-4Q', '世界理解科目'),
    buildEntry('インターネット概論', 2, '1Q', 'ネットワーク基礎'),
    buildEntry('コンピューターサイエンス概論', 2, '1Q', 'CS基礎'),
    buildEntry('Webアプリケーション開発4', 2, '2Q', 'フルスタックWeb構築(Web1~3履修後)'),
    buildEntry('Linux概論', 2, '3Q', 'インフラ基礎(Web4完結後)'),
    buildEntry('オブジェクト指向プログラミング', 2, '3Q', '設計思想(Web4完結後)'),
    buildEntry('コンピュータ概論', 2, '2Q', 'ハードウェア基礎'),
    buildEntry('情報処理概論', 2, '2Q', '情報理論'),
    buildEntry('JavaScriptによる自動化、効率化', 2, '2Q', 'スクリプト実務'),
    buildEntry('機械翻訳実践（法学）', 2, '1-2Q', '多言語要件'),
    buildEntry('戦後日本史1', 2, '3Q', '世界理解科目'),
    buildEntry('データベース運用実践', 2, '4Q', 'DB実践'),
    buildEntry('Javaプログラミング演習', 2, '3-4Q', '考究科目'),
    buildEntry('Webセキュリティ演習', 2, '3-4Q', '考究科目(Web1~4完結後)'),
    buildEntry('機械翻訳実践（情報）', 2, '1-2Q', '多言語要件'),
    buildEntry('プロジェクト実践', 4, '1-4Q', '卒業プロジェクト(1~4Q通年・4単位)'),
  ],

  'デジタルコンテンツ・デザイン表現': [
    buildEntry('アカデミックリテラシー', 1, '1Q', '必修'),
    buildEntry('ITリテラシー', 1, '1Q', '必修'),
    buildEntry('人文社会入門', 1, '1Q', '導入要件'),
    buildEntry('人工知能活用実践', 1, '1-2Q', '導入要件(多言語前提)'),
    buildEntry('経済入門', 1, '2Q', '導入要件'),
    buildEntry('デジタル画像技法論Ⅰ', 1, '1Q', 'pixiv科目'),
    buildEntry('デジタルツールの使い方', 1, '2Q', '必修'),
    buildEntry('多言語ITコミュニケーション', 1, '3Q', '必修(ツール修得後)'),
    buildEntry('マンガ絵コンテから学ぶ視覚表現', 1, '2Q', '世界理解科目'),
    buildEntry('デジタル画像技法論Ⅲ', 1, '2Q', 'pixiv科目'),
    buildEntry('現代社会と数学', 1, '1Q', '【置換】導入選択(社会と数学)'),
    buildEntry('デジタル画像技法論Ⅱ', 1, '3Q', 'pixiv科目'),
    buildEntry('マンガ産業史', 1, '3Q', 'デジタル産業指定要件'),
    buildEntry('世界が変わる編集力', 1, '3Q', '世界理解科目'),
    buildEntry('基礎科目（数理：数学史）', 1, '3Q', '基礎科目要件'),
    buildEntry('基礎科目（情報：情報セキュリティ概論）', 1, '3Q', '基礎科目要件'),
    buildEntry('ビジュアルプログラミング', 1, '3Q', '【追加】ジェネラティブアート前提'),
    buildEntry('アニメ産業史', 1, '4Q', '世界理解科目'),
    buildEntry('近・現代アート概論', 1, '4Q', '世界理解科目'),
    buildEntry('基礎科目（文化・思想：心理学）', 1, '4Q', '基礎科目要件'),
    buildEntry('基礎科目（経済：企業経営）', 1, '4Q', '基礎科目要件'),
    buildEntry('二次創作の歴史から見るネット文化', 1, '3-4Q', '世界理解科目'),
    buildEntry('コンテンツ産業論', 2, '1Q', '世界理解科目'),
    buildEntry('デジタル画像創作論Ⅰ', 2, '1Q', 'pixiv科目'),
    buildEntry('基礎科目（社会・NW：社会学Ⅰ）', 2, '1Q', '基礎科目要件'),
    buildEntry('デジタル画像創作論Ⅱ', 2, '2Q', 'pixiv科目'),
    buildEntry('デジタル画像創作論Ⅲ', 2, '2Q', 'pixiv科目'),
    buildEntry('ジェネラティブアート演習', 2, '1-2Q', '考究科目(プログラミング前提達成)'),
    buildEntry('3Dモデリング技術演習', 2, '1-2Q', '考究科目'),
    buildEntry('アニメのクオリティー管理と商品性', 2, '1-2Q', '考究科目'),
    buildEntry('ネット情報発信概論', 2, '3Q', '社会接続科目'),
    buildEntry('文化人類学Ⅱ', 2, '4Q', '世界理解科目'),
    buildEntry('WEBコミック演習', 2, '3-4Q', '世界理解'),
    buildEntry('マンガの企画立案とプロデュース論', 2, '3-4Q', '考究科目'),
    buildEntry('文化資源のデジタルアーカイブ', 2, '3-4Q', '考究科目'),
    buildEntry('機械翻訳実践（日本研究）', 2, '3-4Q', '多言語要件'),
    buildEntry('機械翻訳実践（異文化理解）', 2, '3-4Q', '多言語要件'),
    buildEntry('プロジェクト実践', 4, '1-4Q', '卒業プロジェクト(1~4Q通年・4単位)'),
  ],

  'ビジネス・マーケティング・イノベーション': [
    buildEntry('アカデミックリテラシー', 1, '1Q', '必修'),
    buildEntry('ITリテラシー', 1, '1Q', '必修'),
    buildEntry('人文社会入門', 1, '1Q', '導入要件'),
    buildEntry('人工知能活用実践', 1, '1-2Q', '導入要件(多言語前提)'),
    buildEntry('経済入門', 1, '2Q', '【追加】経済学・経営学前提(2Q開講)'),
    buildEntry('デジタルツールの使い方', 1, '2Q', '必修'),
    buildEntry('基礎科目（数理：数学の方法）', 1, '2Q', '基礎科目要件'),
    buildEntry('キャリアデザインⅠ（自己理解）', 1, '2Q', '社会接続科目'),
    buildEntry('基礎科目（情報：データサイエンス概論）', 1, '2Q', '基礎科目要件'),
    buildEntry('現代社会と数学', 1, '1Q', '【置換】導入選択(社会と数学)'),
    buildEntry('多言語ITコミュニケーション', 1, '3Q', '必修(ツール修得後)'),
    buildEntry('伝わる論理とコミュニケーション', 1, '3Q', '基礎科目要件'),
    buildEntry('経済言説史', 1, '3Q', '世界理解科目'),
    buildEntry('基礎科目（数理：数学史）', 1, '3Q', '基礎科目要件'),
    buildEntry('IT産業史', 1, '3Q', 'デジタル産業指定要件'),
    buildEntry('統計学入門', 1, '3Q', '【追加】マーケティング分析前提(DS概論修得後)'),
    buildEntry('基礎科目（経済：企業経営）', 1, '4Q', '基礎科目要件(経済入門修得後/4Q履修)'),
    buildEntry('基礎科目（文化・思想：心理学）', 1, '4Q', '基礎科目要件'),
    buildEntry('マルクス経済学', 1, '4Q', '世界理解科目'),
    buildEntry('基礎科目（経済：企業経営）', 1, '4Q', '基礎科目要件'),
    buildEntry('企業経営と会計', 2, '1Q', '世界理解科目(企業経営修得後/1Q履修)'),
    buildEntry('ミクロ経済学', 2, '2Q', '世界理解'),
    buildEntry('マクロ経済学', 2, '1Q', '世界理解科目'),
    buildEntry('コンテンツ産業論', 2, '1Q', '世界理解科目'),
    buildEntry('キャリアデザインⅡ（仕事理解）', 2, '1Q', '社会接続科目'),
    buildEntry('デジタル・マーケティング', 2, '2Q', '世界理解科目'),
    buildEntry('スタートアップ', 2, '2Q', '世界理解科目(企業経営修得後)'),
    buildEntry('意思決定の能力開発', 2, '2Q', '世界理解科目'),
    buildEntry('交渉・合意形成概論', 2, '4Q', '世界理解科目(意思決定修得後)'),
    buildEntry('ネットワーク産業論', 2, '1-2Q', '社会接続科目'),
    buildEntry('機械翻訳実践（法学）', 2, '1-2Q', '多言語要件'),
    buildEntry('戦後日本史1', 2, '3Q', '世界理解科目'),
    buildEntry('農業とデジタルテクノロジー', 2, '4Q', '世界理解科目'),
    buildEntry('マーケティング × データサイエンス', 2, '3-4Q', '考究科目(統計学前提達成)'),
    buildEntry('機械翻訳実践（異文化理解）', 2, '3-4Q', '多言語要件'),
    buildEntry('プロジェクト実践', 4, '1-4Q', '卒業プロジェクト(1~4Q通年・4単位)'),
  ],

  '人文・社会・現代教養': [
    buildEntry('アカデミックリテラシー', 1, '1Q', '必修'),
    buildEntry('ITリテラシー', 1, '1Q', '必修'),
    buildEntry('人文社会入門', 1, '1Q', '導入要件'),
    buildEntry('人工知能活用実践', 1, '1-2Q', '導入要件(多言語前提)'),
    buildEntry('経済入門', 1, '2Q', '導入要件'),
    buildEntry('文化人類学Ⅰ', 1, '1Q', '【追加】文化人類学Ⅱ前提'),
    buildEntry('デジタルツールの使い方', 1, '2Q', '必修'),
    buildEntry('多言語ITコミュニケーション', 1, '3Q', '必修(ツール修得後)'),
    buildEntry('哲学概論', 1, '2Q', '世界理解科目'),
    buildEntry('現代社会と数学', 1, '1Q', '【置換】導入選択(社会と数学)'),
    buildEntry('日本文学Ⅰ', 1, '3Q', '基礎科目要件'),
    buildEntry('基礎科目（社会・NW：社会学Ⅰ）', 1, '3Q', '基礎科目要件'),
    buildEntry('基礎科目（数理：数学史）', 1, '3Q', '基礎科目要件'),
    buildEntry('世界が変わる編集力', 1, '3Q', '世界理解科目'),
    buildEntry('マンガ産業史', 1, '3Q', 'デジタル産業指定要件'),
    buildEntry('基礎科目（情報：情報セキュリティ概論）', 1, '3Q', '基礎科目要件'),
    buildEntry('公共哲学', 1, '4Q', '世界理解科目'),
    buildEntry('マルクス経済学', 1, '4Q', '世界理解科目'),
    buildEntry('基礎科目（経済：企業経営）', 1, '4Q', '基礎科目要件'),
    buildEntry('政治を超える哲学Ⅰ', 1, '3-4Q', '考究科目'),
    buildEntry('生きてゆくための禅', 1, '3-4Q', '世界理解科目'),
    buildEntry('大学とメディアの人類史', 2, '1Q', '世界理解科目'),
    buildEntry('情報社会論', 2, '1Q', '世界理解科目'),
    buildEntry('科学哲学', 2, '1Q', '世界理解科目'),
    buildEntry('社会学Ⅱ', 2, '2Q', '世界理解'),
    buildEntry('日本文学Ⅱ', 2, '2Q', '世界理解科目'),
    buildEntry('文化人類学Ⅱ', 2, '2Q', '世界理解(Ⅰ修得後)'),
    buildEntry('意思決定の能力開発', 2, '2Q', '世界理解科目'),
    buildEntry('政治を超える哲学Ⅱ', 2, '1-2Q', '考究科目'),
    buildEntry('ジェンダー論', 2, '3Q', '世界理解科目'),
    buildEntry('戦後日本史1', 2, '3Q', '世界理解科目'),
    buildEntry('現代資本主義論', 2, '3-4Q', '考究科目(マルクス経済学修得後/3-4Q演習)'),
    buildEntry('機械翻訳実践（日本研究）', 2, '3-4Q', '多言語要件'),
    buildEntry('機械翻訳実践（異文化理解）', 2, '3-4Q', '多言語要件'),
    buildEntry('プロジェクト実践', 4, '1-4Q', '卒業プロジェクト(1~4Q通年・4単位)'),
  ],

  '現代数理科学・理論探究': [
    buildEntry('アカデミックリテラシー', 1, '1Q', '必修'),
    buildEntry('ITリテラシー', 1, '1Q', '必修'),
    buildEntry('人文社会入門', 1, '1Q', '導入要件'),
    buildEntry('人工知能活用実践', 1, '1-2Q', '導入要件(多言語前提)'),
    buildEntry('経済入門', 1, '2Q', '導入要件'),
    buildEntry('デジタルツールの使い方', 1, '2Q', '必修'),
    buildEntry('多言語ITコミュニケーション', 1, '3Q', '必修(ツール修得後)'),
    buildEntry('数学の方法', 1, '2Q', '展開科目'),
    buildEntry('現代社会と数学', 1, '1Q', '【置換】導入選択(社会と数学)'),
    buildEntry('線形代数1', 1, '3Q', '基盤数理'),
    buildEntry('初等代数概論', 1, '3Q', '展開科目'),
    buildEntry('基礎科目（情報：情報セキュリティ概論）', 1, '3Q', '基礎科目要件'),
    buildEntry('マンガ産業史', 1, '3Q', 'デジタル産業指定要件'),
    buildEntry('解析学1', 1, '4Q', '基盤数理'),
    buildEntry('数学的思考とは何か', 1, '4Q', '【追加】数理構造発展前提'),
    buildEntry('Inter-universal Teichmüller Theory 1（宇宙際タイヒミューラー理論 1）', 1, '3-4Q', '先端数理(IUT1)'),
    buildEntry('基礎科目（経済：企業経営）', 1, '4Q', '基礎科目要件'),
    buildEntry('線形代数2', 2, '1Q', '基盤数理'),
    buildEntry('基礎科目（文化・思想：日本文学Ⅰ）', 2, '1Q', '基礎科目要件'),
    buildEntry('機械翻訳実践（情報）', 2, '1-2Q', '多言語要件'),
    buildEntry('解析学2', 2, '2Q', '基盤数理'),
    buildEntry('日常に現れる物理学', 2, '2Q', '展開科目(力学前提)'),
    buildEntry('集合と論理', 2, '3Q', '【追加】論理・構造前提(1Q/3Q開講)'),
    buildEntry('解析学3', 2, '3Q', '基盤数理(1Q/3Q開講)'),
    buildEntry('力学', 2, '3Q', '物理数理(日常物理・解析1修得後/3Q開講)'),
    buildEntry('科学哲学', 2, '3Q', '世界理解'),
    buildEntry('基礎科目（社会・NW：社会学Ⅰ）', 2, '3Q', '基礎科目要件'),
    buildEntry('記号論理', 2, '4Q', '数理論理(集合と論理修得後/4Q履修)'),
    buildEntry('数理構造の発見と活用', 2, '4Q', '展開科目(集合と論理・思考修得後/4Q履修)'),
    buildEntry('数理科学発展演習Ⅰ', 2, '3-4Q', '考究科目(基礎数理完結後)'),
    buildEntry('機械翻訳実践（自然科学）', 2, '3-4Q', '多言語要件'),
    buildEntry('プロジェクト実践', 4, '1-4Q', '卒業プロジェクト(1~4Q通年・4単位)'),
  ],

  '地域創生・アグリ＆スマートローカル': [
    buildEntry('アカデミックリテラシー', 1, '1Q', '必修'),
    buildEntry('ITリテラシー', 1, '1Q', '必修'),
    buildEntry('人文社会入門', 1, '1Q', '導入要件'),
    buildEntry('人工知能活用実践', 1, '1-2Q', '導入要件(多言語前提)'),
    buildEntry('デジタルツールの使い方', 1, '2Q', '必修'),
    buildEntry('多言語ITコミュニケーション', 1, '3Q', '必修(ツール修得後)'),
    buildEntry('経済入門', 1, '2Q', '【追加】地域イノベーション・経済前提'),
    buildEntry('基礎科目（情報：データサイエンス概論）', 1, '2Q', '基礎科目要件'),
    buildEntry('現代社会と数学', 1, '1Q', '【置換】導入選択(社会と数学)'),
    buildEntry('伝わる論理とコミュニケーション', 1, '3Q', '基礎科目要件'),
    buildEntry('基礎科目（数理：数学史）', 1, '3Q', '基礎科目要件'),
    buildEntry('経済言説史', 1, '3Q', '世界理解科目'),
    buildEntry('基礎科目（文化・思想：心理学）', 1, '4Q', '基礎科目要件'),
    buildEntry('アニメ産業史', 1, '4Q', 'デジタル産業指定要件'),
    buildEntry('基礎科目（経済：地域課題の解決とイノベーション）', 1, '4Q', '基礎科目(経済入門修得後)'),
    buildEntry('生きてゆくための禅', 1, '3-4Q', '世界理解科目'),
    buildEntry('大学とメディアの人類史', 2, '1Q', '世界理解科目'),
    buildEntry('コンテンツ産業論', 2, '1Q', '世界理解科目'),
    buildEntry('社会学Ⅰ', 2, '1Q', '【追加】社会学Ⅱ前提'),
    buildEntry('社会学Ⅱ', 2, '2Q', '世界理解'),
    buildEntry('ミクロ経済学', 2, '2Q', '世界理解科目(経済入門修得後)'),
    buildEntry('農業とデジタルテクノロジー', 2, '2Q', '世界理解科目'),
    buildEntry('スタートアップ', 2, '2Q', '世界理解科目'),
    buildEntry('公共哲学', 2, '2Q', '世界理解'),
    buildEntry('ネットワーク産業論', 2, '1-2Q', '社会接続科目'),
    buildEntry('戦後日本史1', 2, '3Q', '世界理解科目'),
    buildEntry('意思決定の能力開発', 2, '4Q', '世界理解科目'),
    buildEntry('文化人類学Ⅱ', 2, '4Q', '世界理解科目'),
    buildEntry('子どもと地域づくり', 2, '3-4Q', '考究科目'),
    buildEntry('機械翻訳実践（異文化理解）', 2, '3-4Q', '多言語要件'),
    buildEntry('プロジェクト実践', 4, '1-4Q', '卒業プロジェクト(1~4Q通年・4単位)'),
  ],

  '情報セキュリティ・サイバー社会安全保障': [
    buildEntry('アカデミックリテラシー', 1, '1Q', '必修'),
    buildEntry('ITリテラシー', 1, '1Q', '必修'),
    buildEntry('人文社会入門', 1, '1Q', '導入要件'),
    buildEntry('人工知能活用実践', 1, '1-2Q', '導入要件(多言語前提)'),
    buildEntry('経済入門', 1, '2Q', '導入要件'),
    buildEntry('Webアプリケーション開発1', 1, '1Q', '展開科目'),
    buildEntry('デジタルツールの使い方', 1, '2Q', '必修'),
    buildEntry('多言語ITコミュニケーション', 1, '3Q', '必修(ツール修得後)'),
    buildEntry('Webアプリケーション開発2', 1, '2Q', '【追加】Web開発応用'),
    buildEntry('AI社会の歩き方', 1, '1-2Q', '世界理解科目'),
    buildEntry('基礎科目（情報：情報セキュリティ概論）', 1, '3Q', '基礎科目要件'),
    buildEntry('基礎科目（数理：初等代数概論）', 1, '3Q', '暗号数理の準備'),
    buildEntry('基礎科目（社会・NW：社会学Ⅰ）', 1, '3Q', '基礎科目要件'),
    buildEntry('IT産業史', 1, '3Q', 'デジタル産業指定要件'),
    buildEntry('基礎科目（数理：数学史）', 1, '3Q', '基礎科目要件'),
    buildEntry('Webアプリケーション開発3', 1, '3Q', '【追加】Webセキュリティ前提'),
    buildEntry('基礎科目（経済：企業経営）', 1, '4Q', '基礎科目要件'),
    buildEntry('基礎科目（文化・思想：心理学）', 1, '4Q', '基礎科目要件'),
    buildEntry('情報社会の総合安全保障', 1, '4Q', '世界理解科目'),
    buildEntry('現代社会と数学', 1, '1Q', '【置換】導入選択(社会と数学)'),
    buildEntry('インターネット概論', 2, '1Q', '展開科目'),
    buildEntry('コンピューターサイエンス概論', 2, '1Q', '展開科目'),
    buildEntry('情報社会論', 2, '1Q', '世界理解科目'),
    buildEntry('機械翻訳実践（情報）', 2, '1-2Q', '多言語要件'),
    buildEntry('コンピュータ概論', 2, '2Q', '展開科目'),
    buildEntry('情報処理概論', 2, '2Q', '展開科目'),
    buildEntry('基礎科目（文化・思想：哲学概論）', 2, '2Q', '基礎科目要件'),
    buildEntry('機械翻訳実践（法学）', 2, '1-2Q', '多言語要件'),
    buildEntry('Linux概論', 2, '3Q', '展開科目'),
    buildEntry('戦後日本史1', 2, '3Q', '世界理解科目'),
    buildEntry('意思決定の能力開発', 2, '4Q', '世界理解科目'),
    buildEntry('インターネットのしくみ', 2, '3-4Q', '考究科目'),
    buildEntry('Webセキュリティ演習', 2, '3-4Q', '考究科目(Web1~3完結後)'),
    buildEntry('プロジェクト実践', 4, '1-4Q', '卒業プロジェクト(1~4Q通年・4単位)'),
  ],

  'コンテンツ・プロデュース＆知財メディアビジネス': [
    buildEntry('アカデミックリテラシー', 1, '1Q', '必修'),
    buildEntry('ITリテラシー', 1, '1Q', '必修'),
    buildEntry('人文社会入門', 1, '1Q', '導入要件'),
    buildEntry('人工知能活用実践', 1, '1-2Q', '導入要件(多言語前提)'),
    buildEntry('経済入門', 1, '2Q', '導入要件'),
    buildEntry('デジタルツールの使い方', 1, '2Q', '必修'),
    buildEntry('多言語ITコミュニケーション', 1, '3Q', '必修(ツール修得後)'),
    buildEntry('マンガ絵コンテから学ぶ視覚表現', 1, '2Q', '世界理解科目'),
    buildEntry('現代社会と数学', 1, '1Q', '【置換】導入選択(社会と数学)'),
    buildEntry('マンガ産業史', 1, '3Q', 'デジタル産業指定要件'),
    buildEntry('世界が変わる編集力', 1, '3Q', '世界理解科目'),
    buildEntry('基礎科目（数理：数学史）', 1, '3Q', '基礎科目要件'),
    buildEntry('アニメ産業史', 1, '4Q', 'デジタル産業'),
    buildEntry('基礎科目（文化・思想：心理学）', 1, '4Q', '基礎科目要件'),
    buildEntry('基礎科目（経済：企業経営）', 1, '4Q', '基礎科目要件'),
    buildEntry('二次創作の歴史から見るネット文化', 1, '3-4Q', 'デジタル産業'),
    buildEntry('コンテンツ産業論', 2, '1Q', 'デジタル産業'),
    buildEntry('企業経営と会計', 2, '1Q', '経済・マーケット'),
    buildEntry('基礎科目（社会・NW：社会学Ⅰ）', 2, '1Q', '基礎科目要件'),
    buildEntry('デジタル・マーケティング', 2, '2Q', '経済・マーケット'),
    buildEntry('基礎科目（情報：データサイエンス概論）', 2, '2Q', '基礎科目要件'),
    buildEntry('近・現代アート概論', 2, '2Q', '文化・思想'),
    buildEntry('意思決定の能力開発', 2, '2Q', '【追加】交渉・合意形成前提'),
    buildEntry('アニメのクオリティー管理と商品性', 2, '1-2Q', '考究科目'),
    buildEntry('ネットワーク産業論', 2, '1-2Q', '社会接続科目'),
    buildEntry('対人コミュニケーション論', 2, '4Q', '社会接続科目'),
    buildEntry('交渉・合意形成概論', 2, '4Q', '世界理解(意思決定修得後)'),
    buildEntry('マンガの企画立案とプロデュース論', 2, '3-4Q', '考究科目'),
    buildEntry('文化資源のデジタルアーカイブ', 2, '3-4Q', '考究科目'),
    buildEntry('機械翻訳実践（日本研究）', 2, '3-4Q', '多言語要件'),
    buildEntry('プロジェクト実践', 4, '1-4Q', '卒業プロジェクト(1~4Q通年・4単位)'),
  ],

  '認知科学・ヒューマンインターフェース': [
    buildEntry('アカデミックリテラシー', 1, '1Q', '必修'),
    buildEntry('ITリテラシー', 1, '1Q', '必修'),
    buildEntry('人文社会入門', 1, '1Q', '導入要件'),
    buildEntry('人工知能活用実践', 1, '1-2Q', '導入要件(多言語前提)'),
    buildEntry('経済入門', 1, '2Q', '導入要件'),
    buildEntry('デジタルツールの使い方', 1, '2Q', '必修'),
    buildEntry('多言語ITコミュニケーション', 1, '3Q', '必修(ツール修得後)'),
    buildEntry('基礎科目（文化・思想：心理学）', 1, '2Q', '基礎科目要件'),
    buildEntry('基礎科目（情報：データサイエンス概論）', 1, '2Q', '基礎科目要件'),
    buildEntry('基礎科目（数理：数学の方法）', 1, '2Q', '基礎科目要件'),
    buildEntry('現代社会と数学', 1, '1Q', '【置換】導入選択(社会と数学)'),
    buildEntry('基礎科目（社会・NW：伝わる論理とコミュニケーション）', 1, '3Q', '基礎科目要件'),
    buildEntry('IT産業史', 1, '3Q', 'デジタル産業指定要件'),
    buildEntry('線形代数1', 1, '3Q', '【追加】機械学習・DL前提数学'),
    buildEntry('基礎科目（数理：数学史）', 1, '3Q', '基礎科目要件'),
    buildEntry('Pythonプログラミング', 1, '4Q', 'プログラミング基礎'),
    buildEntry('解析学1', 1, '4Q', '【追加】機械学習・DL前提数学'),
    buildEntry('基礎科目（経済：企業経営）', 1, '4Q', '基礎科目要件'),
    buildEntry('政治を超える哲学Ⅰ', 1, '3-4Q', '考究科目'),
    buildEntry('認知神経科学', 2, '1Q', '脳科学・認知基礎'),
    buildEntry('機械学習概論', 2, '1Q', 'AI基礎(Python・数学修得後)'),
    buildEntry('コンピューターサイエンス概論', 2, '1Q', 'CS基礎'),
    buildEntry('文化人類学Ⅰ', 2, '1Q', '【追加】文化人類学Ⅱ前提'),
    buildEntry('意思決定の能力開発', 2, '2Q', '社会・ネットワーク'),
    buildEntry('哲学概論', 2, '2Q', '文化・思想'),
    buildEntry('文化人類学Ⅱ', 2, '2Q', '文化・思想(Ⅰ修得後)'),
    buildEntry('心理学実験・調査演習', 2, '1-2Q', '考究科目'),
    buildEntry('ディープラーニング1', 2, '3Q', 'AI専門(線形・解析・ML完結後)'),
    buildEntry('科学哲学', 2, '3Q', '文化・思想'),
    buildEntry('ウェルビーイングをデザインする', 2, '3-4Q', '考究科目'),
    buildEntry('機械翻訳実践（異文化理解）', 2, '3-4Q', '多言語要件'),
    buildEntry('プロジェクト実践', 4, '1-4Q', '卒業プロジェクト(1~4Q通年・4単位)'),
  ],

  'ソーシャルデザイン・未来社会構想': [
    buildEntry('アカデミックリテラシー', 1, '1Q', '必修'),
    buildEntry('ITリテラシー', 1, '1Q', '必修'),
    buildEntry('人文社会入門', 1, '1Q', '導入要件'),
    buildEntry('人工知能活用実践', 1, '1-2Q', '導入要件(多言語前提)'),
    buildEntry('経済入門', 1, '2Q', '導入要件'),
    buildEntry('デジタルツールの使い方', 1, '2Q', '必修'),
    buildEntry('多言語ITコミュニケーション', 1, '3Q', '必修(ツール修得後)'),
    buildEntry('基礎科目（社会・NW：社会学Ⅰ）', 1, '3Q', '基礎科目要件(人文社会修得後)'),
    buildEntry('哲学概論', 1, '2Q', '【追加】科学哲学前提'),
    buildEntry('AI社会の歩き方', 1, '1-2Q', '世界理解科目'),
    buildEntry('世界が変わる編集力', 1, '3Q', '世界理解科目'),
    buildEntry('基礎科目（数理：数学史）', 1, '3Q', '基礎科目要件'),
    buildEntry('基礎科目（情報：情報セキュリティ概論）', 1, '3Q', '基礎科目要件'),
    buildEntry('マンガ産業史', 1, '3Q', 'デジタル産業指定要件'),
    buildEntry('文化人類学Ⅰ', 1, '3Q', '【追加】文化人類学Ⅱ前提'),
    buildEntry('マルクス経済学', 1, '4Q', '世界理解科目'),
    buildEntry('基礎科目（経済：企業経営）', 1, '4Q', '基礎科目要件'),
    buildEntry('基礎科目（文化・思想：心理学）', 1, '4Q', '基礎科目要件'),
    buildEntry('現代社会と数学', 1, '1Q', '【置換】導入選択(社会と数学)'),
    buildEntry('大学とメディアの人類史', 2, '1Q', '社会・ネットワーク'),
    buildEntry('基礎科目（経済：経済言説史）', 2, '1Q', '基礎科目要件'),
    buildEntry('科学哲学', 2, '1Q', '文化・思想(哲学概論修得後)'),
    buildEntry('社会学Ⅱ', 2, '2Q', '社会・NW(社会学Ⅰ修得後)'),
    buildEntry('公共哲学', 2, '2Q', '文化・思想'),
    buildEntry('意思決定の能力開発', 2, '2Q', '社会・ネットワーク'),
    buildEntry('文化人類学Ⅱ', 2, '2Q', '文化・思想(Ⅰ修得後)'),
    buildEntry('SFから考える未来ビジョン', 2, '1-2Q', '考究科目'),
    buildEntry('機械翻訳実践（法学）', 2, '1-2Q', '多言語要件'),
    buildEntry('ジェンダー論', 2, '3Q', '社会・ネットワーク'),
    buildEntry('情報社会論', 2, '3Q', '社会・ネットワーク'),
    buildEntry('未来社会デザイン論', 2, '3-4Q', '考究科目'),
    buildEntry('現代社会理論', 2, '3-4Q', '考究科目'),
    buildEntry('プロジェクト実践', 4, '1-4Q', '卒業プロジェクト(1~4Q通年・4単位)'),
  ],
};

const presetModels = [];

for (const [modelName, courses] of Object.entries(rawModelsData)) {
  const meta = metadataMap[modelName];
  const totalCredits = courses.reduce((sum, item) => sum + item.credits, 0);

  presetModels.push({
    id: meta.id,
    name: modelName,
    tagline: meta.tagline,
    iconName: meta.iconName,
    gradient: meta.gradient,
    totalCoursesCount: courses.length,
    totalCredits,
    courses,
  });
}

const tsContent = `// Auto-generated PERFECT preset models data for ZEN University
export interface PresetCourseEntry {
  subjectRaw: string;
  subjectName: string;
  year: 1 | 2 | 3 | 4;
  quarterStr: string;
  credits: number;
  category: string;
  domain: string;
  notes: string;
}

export interface PresetModel {
  id: string;
  name: string;
  tagline: string;
  iconName: string;
  gradient: string;
  totalCoursesCount: number;
  totalCredits: number;
  courses: PresetCourseEntry[];
}

export const PRESET_MODELS: PresetModel[] = ${JSON.stringify(presetModels, null, 2)};
`;

fs.writeFileSync('./src/data/presetModels.ts', tsContent);
console.log('Successfully generated PERFECT src/data/presetModels.ts!');
